name: Docker Image CI for Rss

on:
   push:
      branches: ['main']
   pull_request:
      branches: ['main']

jobs:
   build_and_publish:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name:
              Build and push the image
              (rss)
           run: |
              cd container/rss-server
              docker login --username mosque-icu --password ${{secrets.GITHUB_TOKEN}} ghcr.io 
              docker build . --tag ghcr.io/mosque-icu/rss:latest 
              docker push ghcr.io/mosque-icu/rss:latest
